name: Deploy NuGet Package to GitHub Releases

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    - name: Build and test
      run: dotnet build --configuration Release
    - name: Run tests
      run: dotnet test --no-build --configuration Release
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    - name: Build and pack NuGet package
      run: dotnet pack --configuration Release

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: 1.0.${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
    - name: Upload NuGet package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./GuerrillaSharp/bin/Release/GuerrillaSharp.1.0.${{ github.run_number }}.nupkg
        asset_name: GuerrillaSharp.1.0.${{ github.run_number }}.nupkg
        asset_content_type: application/octet-stream
