name: Deploy NuGet Package to GitHub Releases

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    - name: Build and test
      run: dotnet build --configuration Release
    - name: Run tests
      run: dotnet test --no-build --configuration Release
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    - name: Build and pack NuGet package
      run: dotnet pack --configuration Release --output nupkg /p:Version=1.0.${{ github.run_number }}

    - name: publish to nuget
      run: |
        dotnet nuget push nupkg/*.nupkg --api-key ${{ secrets.NUGET_SECRET }}  --source https://api.nuget.org/v3/index.json --skip-duplicate
